modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/quinn-semele/quinns-click-through/issues/"

[[mods]]
modId="quinnsclickthrough"
version="${mod_version}"
displayName="Quinn's Click Through"
displayURL="https://modrinth.com/mod/quinns-click-through/"
logoFile="quinnsclickthrough.png"
authors="Quinn Semele"

description='''
Allows you to click through signs and item frames.
'''

[[mixins]]
config="quinnsclickthrough.mixins.json"

[[dependencies.quinnsclickthrough]]
    modId="neoforge" # Can be one of "required" (crashes game), "optional", "incompatible" (crashes game) or "discouraged" (shows warning)
    type="required" #mandatory
    #reason="..." # Why it's incompatible / discouraged?
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE" # NONE, BEFORE, AFTER, self-explanatory
    side="BOTH" # BOTH, CLIENT, SERVER, self-explanatory

[[dependencies.quinnsclickthrough]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
